/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID ece.nitdgp.ac.in)
#  Generated on:      Fri Dec 12 16:01:22 2025
#  Design:            source
#  Command:           saveNetlist ./source_netlist_routing.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Dec 12 2025 15:59:46 IST (Dec 12 2025 10:29:46 UTC)
// Verification Directory fv/source 
module source (
	clk, 
	rst_n, 
	A, 
	B, 
	op, 
	result, 
	carry, 
	zero, 
	sign, 
	overflow);
   input clk;
   input rst_n;
   input [7:0] A;
   input [7:0] B;
   input [2:0] op;
   output [7:0] result;
   output carry;
   output zero;
   output sign;
   output overflow;

   // Internal wires
   wire FE_OFN1_n_162;
   wire FE_OFN0_n_111;
   wire n_1;
   wire n_2;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;
   wire n_132;
   wire n_133;
   wire n_134;
   wire n_135;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_146;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_153;
   wire n_154;
   wire n_155;
   wire n_156;
   wire n_157;
   wire n_158;
   wire n_159;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_163;
   wire n_164;
   wire n_165;
   wire n_187;
   wire n_188;
   wire n_189;
   wire clk1;
   wire rst_n1;
   wire A7;
   wire A6;
   wire A5;
   wire A4;
   wire A3;
   wire A2;
   wire A1;
   wire A0;
   wire B7;
   wire B6;
   wire B5;
   wire B4;
   wire B3;
   wire B2;
   wire B1;
   wire B0;
   wire op2;
   wire op1;
   wire op0;
   wire result7;
   wire result6;
   wire result5;
   wire result4;
   wire result3;
   wire result2;
   wire result1;
   wire result0;
   wire carry1;
   wire zero1;
   wire sign1;
   wire overflow1;

   assign sign = result[7] ;

   buffd1 FE_OFC4_n_162 (.I(n_162),
	.Z(FE_OFN1_n_162));
   inv0d0 FE_OFC3_n_111 (.I(n_111),
	.ZN(FE_OFN0_n_111));
   inv0d0 FE_OFC1_n_75 (.I(n_75),
	.ZN(n_56));
   inv0d1 FE_OFC0_n_70 (.I(n_70),
	.ZN(n_95));
   dfnrq1 zero_reg (.CP(clk),
	.D(n_165),
	.Q(zero));
   dfnrq1 \result_reg[7]  (.CP(clk),
	.D(n_164),
	.Q(result[7]));
   aor31d4 g4518__2398 (.A(FE_OFN1_n_162),
	.B1(n_163),
	.B2(n_157),
	.B3(n_152),
	.Z(n_165));
   dfnrq1 overflow_reg (.CP(clk),
	.D(n_161),
	.Q(overflow));
   nr02d1 g4519__5107 (.A1(n_163),
	.A2(FE_OFN1_n_162),
	.ZN(n_164));
   aon211d2 g4521__6260 (.A(n_159),
	.B(n_143),
	.C1(n_160),
	.C2(A[7]),
	.ZN(n_161));
   dfnrq1 \result_reg[6]  (.CP(clk),
	.D(n_158),
	.Q(result[6]));
   aoi221d1 g4523__4319 (.A(n_77),
	.B1(n_153),
	.B2(op[0]),
	.C1(n_148),
	.C2(n_160),
	.ZN(n_163));
   dfnrq1 carry_reg (.CP(clk),
	.D(n_156),
	.Q(carry));
   nd04d1 g4528__8428 (.A1(n_140),
	.A2(n_155),
	.A3(n_84),
	.A4(rst_n),
	.ZN(n_159));
   nr02d1 g4524__5526 (.A1(FE_OFN1_n_162),
	.A2(n_157),
	.ZN(n_158));
   oai22d2 g4520__6783 (.A1(n_147),
	.A2(n_146),
	.B1(n_149),
	.B2(FE_OFN1_n_162),
	.ZN(n_156));
   oaim22d1 g4533__3680 (.A1(n_154),
	.A2(A[7]),
	.B1(n_154),
	.B2(A[7]),
	.ZN(n_155));
   oai22d1 g4534__1617 (.A1(n_154),
	.A2(n_141),
	.B1(n_63),
	.B2(n_124),
	.ZN(n_153));
   dfnrq1 \result_reg[5]  (.CP(clk),
	.D(n_151),
	.Q(result[5]));
   aoi211d1 g4529__2802 (.A(n_142),
	.B(n_123),
	.C1(n_120),
	.C2(n_130),
	.ZN(n_157));
   nr03d1 g4531__1705 (.A1(n_135),
	.A2(n_137),
	.A3(n_150),
	.ZN(n_152));
   an02d0 g4530__5122 (.A1(n_150),
	.A2(rst_n),
	.Z(n_151));
   aoi22d1 g4526__8246 (.A1(n_136),
	.A2(n_148),
	.B1(n_102),
	.B2(A[0]),
	.ZN(n_149));
   aoi31d1 g4545__7098 (.A(A[7]),
	.B1(n_145),
	.B2(n_39),
	.B3(n_144),
	.ZN(n_147));
   oai311d1 g4546__6131 (.A(n_106),
	.B(rst_n),
	.C1(n_145),
	.C2(n_144),
	.C3(op[2]),
	.ZN(n_146));
   oai211d1 g4525__1881 (.A(n_40),
	.B(n_148),
	.C1(n_160),
	.C2(A[7]),
	.ZN(n_143));
   dfnrq1 \result_reg[4]  (.CP(clk),
	.D(n_138),
	.Q(result[4]));
   oan211d1 g4537__5115 (.A(n_139),
	.B(n_46),
	.C1(n_131),
	.C2(n_141),
	.ZN(n_142));
   aoim22d1 g4547__7482 (.A1(n_145),
	.A2(n_140),
	.B1(n_145),
	.B2(n_140),
	.Z(n_154));
   dfnrq1 \result_reg[3]  (.CP(clk),
	.D(n_134),
	.Q(result[3]));
   aon211d1 g4538__4733 (.A(n_127),
	.B(n_139),
	.C1(n_128),
	.C2(n_57),
	.ZN(n_150));
   an02d0 g4540__6161 (.A1(n_137),
	.A2(rst_n),
	.Z(n_138));
   cg01d1 g4532__9315 (.A(A[7]),
	.B(B[7]),
	.CI(n_132),
	.CO(n_136));
   nd04d1 g4550__9945 (.A1(n_118),
	.A2(n_133),
	.A3(n_108),
	.A4(n_104),
	.ZN(n_135));
   nr02d1 g4548__2883 (.A1(FE_OFN1_n_162),
	.A2(n_133),
	.ZN(n_134));
   mx02d1 g4535__2346 (.I0(n_140),
	.I1(n_76),
	.S(n_132),
	.Z(n_160));
   oai21d1 g4555__1666 (.A(n_32),
	.B1(n_125),
	.B2(n_33),
	.ZN(n_145));
   oai211d1 g4551__7410 (.A(n_116),
	.B(n_103),
	.C1(n_96),
	.C2(n_101),
	.ZN(n_137));
   aoim22d1 g4554__6417 (.A1(n_129),
	.A2(n_130),
	.B1(n_129),
	.B2(n_130),
	.Z(n_131));
   dfnrq1 \result_reg[1]  (.CP(clk),
	.D(n_119),
	.Q(result[1]));
   aoi21d1 g4552__5477 (.A(n_114),
	.B1(n_93),
	.B2(n_139),
	.ZN(n_133));
   aon211d1 g4557__2398 (.A(n_115),
	.B(n_113),
	.C1(n_187),
	.C2(n_126),
	.ZN(n_128));
   aoi311d1 g4539__5107 (.A(n_112),
	.B(n_58),
	.C1(n_110),
	.C2(n_148),
	.C3(n_126),
	.ZN(n_127));
   inv0d1 g4563 (.I(n_129),
	.ZN(n_125));
   aon211d1 g4542__6260 (.A(n_122),
	.B(n_121),
	.C1(n_14),
	.C2(n_124),
	.ZN(n_132));
   oai322d1 g4543__4319 (.A1(n_66),
	.A2(n_25),
	.B1(n_75),
	.B2(n_122),
	.C1(n_121),
	.C2(n_42),
	.C3(n_130),
	.ZN(n_123));
   oaim21d1 g4544__8428 (.A(n_111),
	.B1(n_121),
	.B2(n_95),
	.ZN(n_120));
   dfnrq1 \result_reg[2]  (.CP(clk),
	.D(n_109),
	.Q(result[2]));
   nr02d1 g4568__5526 (.A1(n_118),
	.A2(FE_OFN1_n_162),
	.ZN(n_119));
   oai21d1 g4567__6783 (.A(n_27),
	.B1(n_187),
	.B2(n_38),
	.ZN(n_129));
   aon211d1 g4558__3680 (.A(op[0]),
	.B(n_65),
	.C1(n_99),
	.C2(n_115),
	.ZN(n_116));
   nd03d1 g4559__1617 (.A1(n_107),
	.A2(n_61),
	.A3(n_47),
	.ZN(n_114));
   nr02d1 g4569__2802 (.A1(n_126),
	.A2(n_187),
	.ZN(n_113));
   oan211d1 g4549__1705 (.A(n_126),
	.B(n_111),
	.C1(n_110),
	.C2(n_70),
	.ZN(n_112));
   dfnrq1 \result_reg[0]  (.CP(clk),
	.D(n_105),
	.Q(result[0]));
   nr02d1 g4560__5122 (.A1(n_108),
	.A2(FE_OFN1_n_162),
	.ZN(n_109));
   aon211d1 g4571__8246 (.A(n_106),
	.B(n_94),
	.C1(A[2]),
	.C2(op[2]),
	.ZN(n_107));
   oan211d1 g4576__7098 (.A(n_97),
	.B(n_139),
	.C1(n_51),
	.C2(n_53),
	.ZN(n_118));
   oan211d1 g4553__6131 (.A(n_18),
	.B(n_110),
	.C1(A[5]),
	.C2(B[5]),
	.ZN(n_121));
   inv0d1 g4570 (.I(n_100),
	.ZN(n_108));
   nr02d1 g4581__1881 (.A1(n_104),
	.A2(FE_OFN1_n_162),
	.ZN(n_105));
   aoi322d1 g4565__7482 (.A1(n_102),
	.A2(A[5]),
	.B1(n_56),
	.B2(n_10),
	.C1(n_86),
	.C2(n_148),
	.C3(n_101),
	.ZN(n_103));
   aon211d1 g4573__4733 (.A(n_87),
	.B(n_139),
	.C1(n_81),
	.C2(n_54),
	.ZN(n_100));
   oaim22d1 g4578__6161 (.A1(n_98),
	.A2(n_101),
	.B1(n_98),
	.B2(n_101),
	.ZN(n_99));
   oai211d1 g4584__9315 (.A(n_85),
	.B(n_60),
	.C1(n_74),
	.C2(n_43),
	.ZN(n_97));
   aoi21d1 g4564__9945 (.A(FE_OFN0_n_111),
	.B1(n_91),
	.B2(n_95),
	.ZN(n_96));
   aoi211d1 g4587__2883 (.A(n_79),
	.B(n_41),
	.C1(n_102),
	.C2(A[1]),
	.ZN(n_104));
   oan211d1 g4582__2346 (.A(op[2]),
	.B(n_82),
	.C1(n_83),
	.C2(n_92),
	.ZN(n_94));
   oai31d1 g4562__1666 (.A(n_89),
	.B1(n_88),
	.B2(n_92),
	.B3(n_141),
	.ZN(n_93));
   oai21d1 g4566__7410 (.A(n_9),
	.B1(n_91),
	.B2(n_64),
	.ZN(n_110));
   aon211d1 g4572__6417 (.A(n_92),
	.B(n_55),
	.C1(n_88),
	.C2(n_13),
	.ZN(n_89));
   aoi311d1 g4575__5477 (.A(n_72),
	.B(n_67),
	.C1(n_71),
	.C2(n_148),
	.C3(n_80),
	.ZN(n_87));
   inv0d0 g4577 (.I(n_91),
	.ZN(n_86));
   aoi22d1 g4593__2398 (.A1(n_73),
	.A2(n_84),
	.B1(n_78),
	.B2(A[1]),
	.ZN(n_85));
   aoi21d1 g4588__5107 (.A(n_31),
	.B1(n_83),
	.B2(n_30),
	.ZN(n_98));
   nd02d1 g4589__6260 (.A1(n_83),
	.A2(n_92),
	.ZN(n_82));
   aoim22d1 g4579__4319 (.A1(A[3]),
	.A2(B[3]),
	.B1(n_88),
	.B2(n_7),
	.Z(n_91));
   aon211d1 g4590__8428 (.A(n_115),
	.B(n_48),
	.C1(n_80),
	.C2(n_68),
	.ZN(n_81));
   oaim21d1 g4594__5526 (.A(n_69),
	.B1(n_78),
	.B2(A[0]),
	.ZN(n_79));
   oai222d1 g4596__6783 (.A1(n_111),
	.A2(n_76),
	.B1(n_75),
	.B2(n_12),
	.C1(n_74),
	.C2(n_144),
	.ZN(n_77));
   oai22d1 g4607__3680 (.A1(n_59),
	.A2(n_189),
	.B1(n_52),
	.B2(B[0]),
	.ZN(n_73));
   oan211d1 g4583__1617 (.A(n_80),
	.B(n_111),
	.C1(n_71),
	.C2(n_70),
	.ZN(n_72));
   oai221d1 g4602__2802 (.A(n_49),
	.B1(n_84),
	.B2(n_95),
	.C1(A[0]),
	.C2(B[0]),
	.ZN(n_69));
   oai21d1 g4598__1705 (.A(n_29),
	.B1(n_68),
	.B2(n_37),
	.ZN(n_83));
   oai22d1 g4605__5122 (.A1(n_66),
	.A2(n_62),
	.B1(n_75),
	.B2(n_19),
	.ZN(n_67));
   oai222d1 g4606__8246 (.A1(n_75),
	.A2(n_64),
	.B1(n_63),
	.B2(n_62),
	.C1(n_50),
	.C2(n_8),
	.ZN(n_65));
   aoi22d1 g4608__7098 (.A1(n_78),
	.A2(A[3]),
	.B1(n_102),
	.B2(A[4]),
	.ZN(n_61));
   oai211d1 g4609__6131 (.A(n_106),
	.B(A[0]),
	.C1(n_59),
	.C2(op[2]),
	.ZN(n_60));
   oai22d1 g4610__1881 (.A1(n_66),
	.A2(n_124),
	.B1(n_75),
	.B2(n_17),
	.ZN(n_58));
   aoi222d1 g4611__5115 (.A1(A[5]),
	.A2(n_56),
	.B1(n_55),
	.B2(A[4]),
	.C1(op[1]),
	.C2(B[5]),
	.ZN(n_57));
   aoi222d1 g4604__7482 (.A1(A[2]),
	.A2(n_56),
	.B1(n_55),
	.B2(A[1]),
	.C1(op[1]),
	.C2(B[2]),
	.ZN(n_54));
   oan211d1 g4591__4733 (.A(n_52),
	.B(n_63),
	.C1(n_22),
	.C2(op[1]),
	.ZN(n_53));
   oai322d1 g4592__6161 (.A1(n_75),
	.A2(n_36),
	.B1(n_50),
	.B2(n_15),
	.C1(n_59),
	.C2(n_141),
	.C3(n_49),
	.ZN(n_51));
   nr02d1 g4599__9315 (.A1(n_68),
	.A2(n_80),
	.ZN(n_48));
   aon211d1 g4601__9945 (.A(B[3]),
	.B(n_11),
	.C1(n_56),
	.C2(A[3]),
	.ZN(n_47));
   aoi222d1 g4603__2883 (.A1(A[6]),
	.A2(n_56),
	.B1(n_55),
	.B2(A[5]),
	.C1(op[1]),
	.C2(B[6]),
	.ZN(n_46));
   oan211d1 g4585__2346 (.A(n_20),
	.B(n_71),
	.C1(A[2]),
	.C2(B[2]),
	.ZN(n_88));
   inv0d0 g4616 (.I(n_59),
	.ZN(n_52));
   aoi22d1 g4614__1666 (.A1(n_189),
	.A2(n_188),
	.B1(n_43),
	.B2(A[1]),
	.ZN(n_68));
   nd02d1 g4621__7410 (.A1(n_95),
	.A2(op[2]),
	.ZN(n_111));
   inv0d0 g4617 (.I(n_148),
	.ZN(n_42));
   oai22d1 g4597__6417 (.A1(n_75),
	.A2(n_49),
	.B1(n_74),
	.B2(n_1),
	.ZN(n_41));
   nr02d1 g4600__5477 (.A1(FE_OFN1_n_162),
	.A2(n_140),
	.ZN(n_40));
   inv0d0 g4618 (.I(n_102),
	.ZN(n_66));
   an02d1 g4620__2398 (.A1(n_106),
	.A2(n_39),
	.Z(n_84));
   nr02d1 g4627__5107 (.A1(n_26),
	.A2(n_38),
	.ZN(n_126));
   nr02d1 g4626__6260 (.A1(n_28),
	.A2(n_37),
	.ZN(n_80));
   nr02d1 g4622__4319 (.A1(n_35),
	.A2(n_21),
	.ZN(n_59));
   nr02d1 g4623__8428 (.A1(op[2]),
	.A2(n_70),
	.ZN(n_148));
   inv0d0 g4613 (.I(n_140),
	.ZN(n_76));
   nr02d1 g4619__5526 (.A1(n_139),
	.A2(n_75),
	.ZN(n_78));
   oai21d1 g4595__6783 (.A(n_36),
	.B1(n_35),
	.B2(n_49),
	.ZN(n_71));
   nr02d1 g4628__3680 (.A1(n_34),
	.A2(n_23),
	.ZN(n_101));
   nd12d1 g4629__1617 (.A1(n_33),
	.A2(n_32),
	.ZN(n_130));
   nd12d1 g4630__2802 (.A1(n_31),
	.A2(n_30),
	.ZN(n_92));
   inv0d0 g4632 (.I(n_28),
	.ZN(n_29));
   inv0d0 g4654 (.I(n_26),
	.ZN(n_27));
   inv0d0 g4638 (.I(n_141),
	.ZN(n_115));
   oai22d1 g4631__1705 (.A1(n_25),
	.A2(B[7]),
	.B1(n_144),
	.B2(A[7]),
	.ZN(n_140));
   inv0d0 g4656 (.I(n_55),
	.ZN(n_63));
   nr02d1 g4624__5122 (.A1(op[0]),
	.A2(n_50),
	.ZN(n_102));
   inv0d0 g4612 (.I(n_49),
	.ZN(n_22));
   inv0d0 g4636 (.I(n_36),
	.ZN(n_21));
   inv0d0 g4633 (.I(n_19),
	.ZN(n_20));
   inv0d0 g4635 (.I(n_17),
	.ZN(n_18));
   nr02d1 g4644__7098 (.A1(B[2]),
	.A2(n_15),
	.ZN(n_28));
   nr02d1 g4666__6131 (.A1(A[6]),
	.A2(n_14),
	.ZN(n_33));
   nr02d1 g4661__1881 (.A1(B[5]),
	.A2(n_6),
	.ZN(n_26));
   nr02d1 g4660__5115 (.A1(B[3]),
	.A2(n_62),
	.ZN(n_31));
   nd02d0 g4653__4733 (.A1(n_13),
	.A2(n_139),
	.ZN(n_70));
   nd02d1 g4652__6161 (.A1(n_13),
	.A2(n_39),
	.ZN(n_141));
   oai21d1 g4625__9315 (.A(A[7]),
	.B1(B[7]),
	.B2(op[0]),
	.ZN(n_12));
   inv0d0 g4637 (.I(n_74),
	.ZN(n_11));
   inv0d0 g4634 (.I(n_9),
	.ZN(n_10));
   nr02d1 g4664__9945 (.A1(A[4]),
	.A2(n_8),
	.ZN(n_23));
   nr02d0 g4663__2883 (.A1(A[5]),
	.A2(n_2),
	.ZN(n_38));
   nd02d1 g4665__2346 (.A1(n_62),
	.A2(B[3]),
	.ZN(n_30));
   nr02d0 g4662__1666 (.A1(A[2]),
	.A2(n_5),
	.ZN(n_37));
   nr02d1 g4659__7410 (.A1(B[4]),
	.A2(n_4),
	.ZN(n_34));
   nd02d1 g4643__6417 (.A1(n_14),
	.A2(A[6]),
	.ZN(n_32));
   nr02d1 g4668__5477 (.A1(op[1]),
	.A2(n_139),
	.ZN(n_106));
   nr02d1 g4670__2398 (.A1(op[1]),
	.A2(n_39),
	.ZN(n_55));
   nd02d1 g4671__5107 (.A1(n_39),
	.A2(op[1]),
	.ZN(n_75));
   nr02d1 g4640__6260 (.A1(B[3]),
	.A2(A[3]),
	.ZN(n_7));
   nr02d1 g4645__4319 (.A1(B[4]),
	.A2(A[4]),
	.ZN(n_64));
   nd02d1 g4642__8428 (.A1(A[6]),
	.A2(B[6]),
	.ZN(n_122));
   nd02d1 g4649__5526 (.A1(op[2]),
	.A2(op[1]),
	.ZN(n_50));
   nd02d1 g4669__6783 (.A1(A[0]),
	.A2(B[0]),
	.ZN(n_49));
   nd02d1 g4648__3680 (.A1(A[5]),
	.A2(B[5]),
	.ZN(n_17));
   nd02d1 g4647__1617 (.A1(A[4]),
	.A2(B[4]),
	.ZN(n_9));
   nr02d1 g4641__2802 (.A1(B[1]),
	.A2(A[1]),
	.ZN(n_35));
   nd02d1 g4646__1705 (.A1(A[2]),
	.A2(B[2]),
	.ZN(n_19));
   nd02d1 g4650__5122 (.A1(A[1]),
	.A2(B[1]),
	.ZN(n_36));
   nd02d1 g4651__8246 (.A1(op[1]),
	.A2(op[0]),
	.ZN(n_74));
   inv0d0 g4677 (.I(A[5]),
	.ZN(n_6));
   inv0d0 g4672 (.I(B[2]),
	.ZN(n_5));
   inv0d0 g4684 (.I(A[4]),
	.ZN(n_4));
   inv0d0 g4682 (.I(B[5]),
	.ZN(n_2));
   inv0d0 g4681 (.I(B[0]),
	.ZN(n_1));
   inv0d1 g4680 (.I(B[1]),
	.ZN(n_43));
   inv0d0 g4675 (.I(A[2]),
	.ZN(n_15));
   inv0d0 g4686 (.I(B[7]),
	.ZN(n_144));
   inv0d0 g4673 (.I(B[4]),
	.ZN(n_8));
   inv0d0 g4687 (.I(A[7]),
	.ZN(n_25));
   inv0d0 g4683 (.I(B[6]),
	.ZN(n_14));
   inv0d0 g4679 (.I(op[1]),
	.ZN(n_13));
   inv0d0 g4676 (.I(A[6]),
	.ZN(n_124));
   inv0d0 g4678 (.I(A[3]),
	.ZN(n_62));
   inv0d1 g4688 (.I(op[2]),
	.ZN(n_39));
   inv0d1 g4690 (.I(op[0]),
	.ZN(n_139));
   inv0d0 g4689 (.I(rst_n),
	.ZN(n_162));
   aoim21d1 g2 (.A(n_34),
	.B1(n_98),
	.B2(n_23),
	.ZN(n_187));
   nd12d1 g4702 (.A1(A[1]),
	.A2(B[1]),
	.ZN(n_188));
   nd12d1 g4703 (.A1(A[0]),
	.A2(B[0]),
	.ZN(n_189));
   pc3c01 pclk (.CCLK(clk),
	.CP(clk1));
   pc3d01 prst_n (.PAD(rst_n),
	.CIN(rst_n1));
   pc3d01 pA_7 (.PAD(A[7]),
	.CIN(A7));
   pc3d01 pA_6 (.PAD(A[6]),
	.CIN(A6));
   pc3d01 pA_5 (.PAD(A[5]),
	.CIN(A5));
   pc3d01 pA_4 (.PAD(A[4]),
	.CIN(A4));
   pc3d01 pA_3 (.PAD(A[3]),
	.CIN(A3));
   pc3d01 pA_2 (.PAD(A[2]),
	.CIN(A2));
   pc3d01 pA_1 (.PAD(A[1]),
	.CIN(A1));
   pc3d01 pA_0 (.PAD(A[0]),
	.CIN(A0));
   pc3d01 pB_7 (.PAD(B[7]),
	.CIN(B7));
   pc3d01 pB_6 (.PAD(B[6]),
	.CIN(B6));
   pc3d01 pB_5 (.PAD(B[5]),
	.CIN(B5));
   pc3d01 pB_4 (.PAD(B[4]),
	.CIN(B4));
   pc3d01 pB_3 (.PAD(B[3]),
	.CIN(B3));
   pc3d01 pB_2 (.PAD(B[2]),
	.CIN(B2));
   pc3d01 pB_1 (.PAD(B[1]),
	.CIN(B1));
   pc3d01 pB_0 (.PAD(B[0]),
	.CIN(B0));
   pc3d01 pop_2 (.PAD(op[2]),
	.CIN(op2));
   pc3d01 pop_1 (.PAD(op[1]),
	.CIN(op1));
   pc3d01 pop_0 (.PAD(op[0]),
	.CIN(op0));
   pc3d01 presult_7 (.PAD(result[7]),
	.CIN(result7));
   pc3d01 presult_6 (.PAD(result[6]),
	.CIN(result6));
   pc3d01 presult_5 (.PAD(result[5]),
	.CIN(result5));
   pc3d01 presult_4 (.PAD(result[4]),
	.CIN(result4));
   pc3d01 presult_3 (.PAD(result[3]),
	.CIN(result3));
   pc3d01 presult_2 (.PAD(result[2]),
	.CIN(result2));
   pc3d01 presult_1 (.PAD(result[1]),
	.CIN(result1));
   pc3d01 presult_0 (.PAD(result[0]),
	.CIN(result0));
   pc3d01 pcarry (.PAD(carry),
	.CIN(carry1));
   pc3d01 pzero (.PAD(zero),
	.CIN(zero1));
   pc3d01 psign (.PAD(sign),
	.CIN(sign1));
   pc3d01 poverflow (.PAD(overflow),
	.CIN(overflow1));
endmodule

