/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID ece.nitdgp.ac.in)
#  Generated on:      Thu May 21 13:04:57 2026
#  Design:            alu_top
#  Command:           saveNetlist ./alu_top_netlist_cts.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: May 21 2026 13:04:21 IST (May 21 2026 07:34:21 UTC)
// Verification Directory fv/alu_top 
module alu_top (
	clk, 
	a, 
	b, 
	cin, 
	opcode, 
	result, 
	cout, 
	zero);
   input clk;
   input [7:0] a;
   input [7:0] b;
   input cin;
   input [2:0] opcode;
   output [7:0] result;
   output cout;
   output zero;

   // Internal wires
   wire FE_OFN1_n_73;
   wire FE_OCPN0_n_67;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire clk1;
   wire cin1;
   wire a7;
   wire a6;
   wire a5;
   wire a4;
   wire a3;
   wire a2;
   wire a1;
   wire a0;
   wire b7;
   wire b6;
   wire b5;
   wire b4;
   wire b3;
   wire b2;
   wire b1;
   wire b0;
   wire opcode2;
   wire opcode1;
   wire opcode0;
   wire result7;
   wire result6;
   wire result5;
   wire result4;
   wire result3;
   wire result2;
   wire result1;
   wire result0;
   wire cout1;
   wire zero1;

   buffd1 FE_OFC1_n_73 (.I(n_73),
	.Z(FE_OFN1_n_73));
   bufbd3 FE_OCPC0_n_67 (.I(n_67),
	.Z(FE_OCPN0_n_67));
   nr04d1 g1708__2398 (.A1(result[5]),
	.A2(result[6]),
	.A3(n_75),
	.A4(FE_OCPN0_n_67),
	.ZN(zero));
   or02d7 g1709__5107 (.A1(result[0]),
	.A2(result[7]),
	.Z(n_75));
   dfnrq1 \result_reg[7]  (.CP(clk),
	.D(n_74),
	.Q(result[7]));
   dfnrq1 cout_reg (.CP(clk),
	.D(FE_OFN1_n_73),
	.Q(cout));
   oai211d1 g1712__6260 (.A(n_15),
	.B(n_31),
	.C1(n_71),
	.C2(n_72),
	.ZN(n_74));
   dfnrq1 \result_reg[6]  (.CP(clk),
	.D(n_68),
	.Q(result[6]));
   oan211d1 g1714__4319 (.A(n_72),
	.B(n_4),
	.C1(n_70),
	.C2(n_30),
	.ZN(n_73));
   aoim22d1 g1716__8428 (.A1(n_70),
	.A2(n_69),
	.B1(n_70),
	.B2(n_69),
	.Z(n_71));
   oai211d1 g1715__5526 (.A(n_17),
	.B(n_39),
	.C1(n_65),
	.C2(n_72),
	.ZN(n_68));
   dfnrq1 \result_reg[5]  (.CP(clk),
	.D(n_66),
	.Q(result[5]));
   or04d0 g1718__6783 (.A1(result[1]),
	.A2(result[2]),
	.A3(result[3]),
	.A4(result[4]),
	.Z(n_67));
   aoim21d1 g1719__3680 (.A(n_37),
	.B1(n_64),
	.B2(n_35),
	.ZN(n_70));
   oai211d1 g1720__1617 (.A(n_18),
	.B(n_21),
	.C1(n_61),
	.C2(n_72),
	.ZN(n_66));
   aoim22d1 g1721__2802 (.A1(n_64),
	.A2(n_63),
	.B1(n_64),
	.B2(n_63),
	.Z(n_65));
   dfnrq1 \result_reg[4]  (.CP(clk),
	.D(n_62),
	.Q(result[4]));
   aoim21d1 g1723__1705 (.A(n_20),
	.B1(n_60),
	.B2(n_19),
	.ZN(n_64));
   oai211d1 g1724__5122 (.A(n_7),
	.B(n_10),
	.C1(n_57),
	.C2(n_72),
	.ZN(n_62));
   aoim22d1 g1725__8246 (.A1(n_60),
	.A2(n_59),
	.B1(n_60),
	.B2(n_59),
	.Z(n_61));
   dfnrq1 \result_reg[3]  (.CP(clk),
	.D(n_58),
	.Q(result[3]));
   aoim21d1 g1727__7098 (.A(n_9),
	.B1(n_56),
	.B2(n_8),
	.ZN(n_60));
   oai211d1 g1728__6131 (.A(n_24),
	.B(n_13),
	.C1(n_53),
	.C2(n_72),
	.ZN(n_58));
   aoim22d1 g1729__1881 (.A1(n_56),
	.A2(n_55),
	.B1(n_56),
	.B2(n_55),
	.Z(n_57));
   dfnrq1 \result_reg[2]  (.CP(clk),
	.D(n_54),
	.Q(result[2]));
   aoim21d1 g1731__5115 (.A(n_12),
	.B1(n_52),
	.B2(n_11),
	.ZN(n_56));
   oai211d1 g1732__7482 (.A(n_14),
	.B(n_42),
	.C1(n_49),
	.C2(n_72),
	.ZN(n_54));
   aoim22d1 g1733__4733 (.A1(n_52),
	.A2(n_51),
	.B1(n_52),
	.B2(n_51),
	.Z(n_53));
   dfnrq1 \result_reg[1]  (.CP(clk),
	.D(n_50),
	.Q(result[1]));
   oai211d1 g1736__6161 (.A(n_25),
	.B(n_34),
	.C1(n_45),
	.C2(n_72),
	.ZN(n_50));
   aoim21d1 g1735__9315 (.A(n_41),
	.B1(n_48),
	.B2(n_40),
	.ZN(n_52));
   aoim22d1 g1737__9945 (.A1(n_48),
	.A2(n_47),
	.B1(n_48),
	.B2(n_47),
	.Z(n_49));
   dfnrq1 \result_reg[0]  (.CP(clk),
	.D(n_46),
	.Q(result[0]));
   oai211d1 g1740__2883 (.A(n_16),
	.B(n_29),
	.C1(n_28),
	.C2(n_72),
	.ZN(n_46));
   aoim21d1 g1739__2346 (.A(n_33),
	.B1(n_44),
	.B2(n_32),
	.ZN(n_48));
   aoim22d1 g1741__1666 (.A1(n_44),
	.A2(n_43),
	.B1(n_44),
	.B2(n_43),
	.Z(n_45));
   aoim22d1 g1758__7410 (.A1(n_38),
	.A2(n_41),
	.B1(n_36),
	.B2(n_40),
	.Z(n_42));
   aoim22d1 g1755__6417 (.A1(n_38),
	.A2(n_37),
	.B1(n_36),
	.B2(n_35),
	.Z(n_39));
   aoim22d1 g1756__5477 (.A1(n_38),
	.A2(n_33),
	.B1(n_36),
	.B2(n_32),
	.Z(n_34));
   aoim22d1 g1757__2398 (.A1(n_38),
	.A2(n_3),
	.B1(n_36),
	.B2(n_30),
	.Z(n_31));
   aoi22d1 g1754__5107 (.A1(n_2),
	.A2(n_5),
	.B1(n_38),
	.B2(n_6),
	.ZN(n_29));
   aoim22d1 g1759__6260 (.A1(n_27),
	.A2(n_26),
	.B1(n_27),
	.B2(n_26),
	.Z(n_28));
   aoim22d1 g1742__4319 (.A1(n_43),
	.A2(n_23),
	.B1(n_22),
	.B2(a[1]),
	.Z(n_25));
   aoim22d1 g1743__8428 (.A1(n_51),
	.A2(n_23),
	.B1(n_22),
	.B2(a[3]),
	.Z(n_24));
   aoim22d1 g1753__5526 (.A1(n_38),
	.A2(n_20),
	.B1(n_36),
	.B2(n_19),
	.Z(n_21));
   aoim22d1 g1745__6783 (.A1(n_59),
	.A2(n_23),
	.B1(n_22),
	.B2(a[5]),
	.Z(n_18));
   aoim22d1 g1746__3680 (.A1(n_63),
	.A2(n_23),
	.B1(n_22),
	.B2(a[6]),
	.Z(n_17));
   aoim22d1 g1747__1617 (.A1(n_27),
	.A2(n_23),
	.B1(n_22),
	.B2(a[0]),
	.Z(n_16));
   aoim22d1 g1748__2802 (.A1(n_69),
	.A2(n_23),
	.B1(n_22),
	.B2(a[7]),
	.Z(n_15));
   aoim22d1 g1749__1705 (.A1(n_47),
	.A2(n_23),
	.B1(n_22),
	.B2(a[2]),
	.Z(n_14));
   aoim22d1 g1751__5122 (.A1(n_38),
	.A2(n_12),
	.B1(n_36),
	.B2(n_11),
	.Z(n_13));
   aoim22d1 g1752__8246 (.A1(n_38),
	.A2(n_9),
	.B1(n_36),
	.B2(n_8),
	.Z(n_10));
   aoim22d1 g1744__7098 (.A1(n_55),
	.A2(n_23),
	.B1(n_22),
	.B2(a[4]),
	.Z(n_7));
   aoi21d1 g1750__6131 (.A(n_6),
	.B1(n_5),
	.B2(cin),
	.ZN(n_44));
   inv0d0 g1760 (.I(n_3),
	.ZN(n_4));
   ah01d1 g1761__1881 (.A(a[7]),
	.B(b[7]),
	.CO(n_3),
	.S(n_69));
   ah01d1 g1768__5115 (.A(a[6]),
	.B(b[6]),
	.CO(n_37),
	.S(n_63));
   ah01d1 g1767__7482 (.A(a[5]),
	.B(b[5]),
	.CO(n_20),
	.S(n_59));
   ah01d1 g1766__4733 (.A(a[4]),
	.B(b[4]),
	.CO(n_9),
	.S(n_55));
   ah01d1 g1765__6161 (.A(a[3]),
	.B(b[3]),
	.CO(n_12),
	.S(n_51));
   ah01d1 g1764__9315 (.A(a[2]),
	.B(b[2]),
	.CO(n_41),
	.S(n_47));
   ah01d1 g1763__9945 (.A(a[1]),
	.B(b[1]),
	.CO(n_33),
	.S(n_43));
   ah01d1 g1762__2883 (.A(a[0]),
	.B(b[0]),
	.CO(n_6),
	.S(n_27));
   inv0d0 g1770 (.I(n_36),
	.ZN(n_2));
   nd02d1 g1774__2346 (.A1(n_1),
	.A2(opcode[0]),
	.ZN(n_36));
   nr02d1 g1775__1666 (.A1(opcode[1]),
	.A2(n_0),
	.ZN(n_38));
   nr02d1 g1782__7410 (.A1(opcode[0]),
	.A2(n_1),
	.ZN(n_23));
   or03d1 g1769__6417 (.A1(opcode[1]),
	.A2(opcode[2]),
	.A3(opcode[0]),
	.Z(n_72));
   nr02d1 g1777__5477 (.A1(b[6]),
	.A2(a[6]),
	.ZN(n_35));
   nr02d1 g1771__2398 (.A1(b[2]),
	.A2(a[2]),
	.ZN(n_40));
   or02d0 g1773__5107 (.A1(a[0]),
	.A2(b[0]),
	.Z(n_5));
   nr02d1 g1781__6260 (.A1(b[4]),
	.A2(a[4]),
	.ZN(n_8));
   nr02d1 g1780__4319 (.A1(b[5]),
	.A2(a[5]),
	.ZN(n_19));
   nr02d1 g1778__8428 (.A1(b[3]),
	.A2(a[3]),
	.ZN(n_11));
   nr02d1 g1779__5526 (.A1(b[7]),
	.A2(a[7]),
	.ZN(n_30));
   nr02d1 g1772__6783 (.A1(b[1]),
	.A2(a[1]),
	.ZN(n_32));
   nd02d1 g1776__3680 (.A1(opcode[1]),
	.A2(opcode[0]),
	.ZN(n_22));
   inv0d0 g1783 (.I(cin),
	.ZN(n_26));
   inv0d0 g1784 (.I(opcode[2]),
	.ZN(n_0));
   inv0d0 g1785 (.I(opcode[1]),
	.ZN(n_1));
   pc3c01 pclk (.CCLK(clk),
	.CP(clk1));
   pc3d01 pcin (.PAD(cin),
	.CIN(cin1));
   pc3d01 pa_7 (.PAD(a[7]),
	.CIN(a7));
   pc3d01 pa_6 (.PAD(a[6]),
	.CIN(a6));
   pc3d01 pa_5 (.PAD(a[5]),
	.CIN(a5));
   pc3d01 pa_4 (.PAD(a[4]),
	.CIN(a4));
   pc3d01 pa_3 (.PAD(a[3]),
	.CIN(a3));
   pc3d01 pa_2 (.PAD(a[2]),
	.CIN(a2));
   pc3d01 pa_1 (.PAD(a[1]),
	.CIN(a1));
   pc3d01 pa_0 (.PAD(a[0]),
	.CIN(a0));
   pc3d01 pb_7 (.PAD(b[7]),
	.CIN(b7));
   pc3d01 pb_6 (.PAD(b[6]),
	.CIN(b6));
   pc3d01 pb_5 (.PAD(b[5]),
	.CIN(b5));
   pc3d01 pb_4 (.PAD(b[4]),
	.CIN(b4));
   pc3d01 pb_3 (.PAD(b[3]),
	.CIN(b3));
   pc3d01 pb_2 (.PAD(b[2]),
	.CIN(b2));
   pc3d01 pb_1 (.PAD(b[1]),
	.CIN(b1));
   pc3d01 pb_0 (.PAD(b[0]),
	.CIN(b0));
   pc3d01 popcode_2 (.PAD(opcode[2]),
	.CIN(opcode2));
   pc3d01 popcode_1 (.PAD(opcode[1]),
	.CIN(opcode1));
   pc3d01 popcode_0 (.PAD(opcode[0]),
	.CIN(opcode0));
   pc3d01 presult_7 (.PAD(result[7]),
	.CIN(result7));
   pc3d01 presult_6 (.PAD(result[6]),
	.CIN(result6));
   pc3d01 presult_5 (.PAD(result[5]),
	.CIN(result5));
   pc3d01 presult_4 (.PAD(result[4]),
	.CIN(result4));
   pc3d01 presult_3 (.PAD(result[3]),
	.CIN(result3));
   pc3d01 presult_2 (.PAD(result[2]),
	.CIN(result2));
   pc3d01 presult_1 (.PAD(result[1]),
	.CIN(result1));
   pc3d01 presult_0 (.PAD(result[0]),
	.CIN(result0));
   pc3d01 pcout (.PAD(cout),
	.CIN(cout1));
   pc3d01 pzero (.PAD(zero),
	.CIN(zero1));
endmodule

