
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: May 21 2026 13:04:21 IST (May 21 2026 07:34:21 UTC)

// Verification Directory fv/alu_top 

module alu_top(clk, a, b, cin, opcode, result, cout, zero);
  input clk, cin;
  input [7:0] a, b;
  input [2:0] opcode;
  output [7:0] result;
  output cout, zero;
  wire clk, cin;
  wire [7:0] a, b;
  wire [2:0] opcode;
  wire [7:0] result;
  wire cout, zero;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75;
  nr04d1 g1708__2398(.A1 (result[5]), .A2 (result[6]), .A3 (n_75), .A4
       (n_67), .ZN (zero));
  or02d0 g1709__5107(.A1 (result[0]), .A2 (result[7]), .Z (n_75));
  dfnrq1 \result_reg[7] (.CP (clk), .D (n_74), .Q (result[7]));
  dfnrq1 cout_reg(.CP (clk), .D (n_73), .Q (cout));
  oai211d1 g1712__6260(.A (n_15), .B (n_31), .C1 (n_71), .C2 (n_72),
       .ZN (n_74));
  dfnrq1 \result_reg[6] (.CP (clk), .D (n_68), .Q (result[6]));
  oan211d1 g1714__4319(.A (n_72), .B (n_4), .C1 (n_70), .C2 (n_30), .ZN
       (n_73));
  aoim22d1 g1716__8428(.A1 (n_70), .A2 (n_69), .B1 (n_70), .B2 (n_69),
       .Z (n_71));
  oai211d1 g1715__5526(.A (n_17), .B (n_39), .C1 (n_65), .C2 (n_72),
       .ZN (n_68));
  dfnrq1 \result_reg[5] (.CP (clk), .D (n_66), .Q (result[5]));
  or04d0 g1718__6783(.A1 (result[1]), .A2 (result[2]), .A3 (result[3]),
       .A4 (result[4]), .Z (n_67));
  aoim21d1 g1719__3680(.A (n_37), .B1 (n_64), .B2 (n_35), .ZN (n_70));
  oai211d1 g1720__1617(.A (n_18), .B (n_21), .C1 (n_61), .C2 (n_72),
       .ZN (n_66));
  aoim22d1 g1721__2802(.A1 (n_64), .A2 (n_63), .B1 (n_64), .B2 (n_63),
       .Z (n_65));
  dfnrq1 \result_reg[4] (.CP (clk), .D (n_62), .Q (result[4]));
  aoim21d1 g1723__1705(.A (n_20), .B1 (n_60), .B2 (n_19), .ZN (n_64));
  oai211d1 g1724__5122(.A (n_7), .B (n_10), .C1 (n_57), .C2 (n_72), .ZN
       (n_62));
  aoim22d1 g1725__8246(.A1 (n_60), .A2 (n_59), .B1 (n_60), .B2 (n_59),
       .Z (n_61));
  dfnrq1 \result_reg[3] (.CP (clk), .D (n_58), .Q (result[3]));
  aoim21d1 g1727__7098(.A (n_9), .B1 (n_56), .B2 (n_8), .ZN (n_60));
  oai211d1 g1728__6131(.A (n_24), .B (n_13), .C1 (n_53), .C2 (n_72),
       .ZN (n_58));
  aoim22d1 g1729__1881(.A1 (n_56), .A2 (n_55), .B1 (n_56), .B2 (n_55),
       .Z (n_57));
  dfnrq1 \result_reg[2] (.CP (clk), .D (n_54), .Q (result[2]));
  aoim21d1 g1731__5115(.A (n_12), .B1 (n_52), .B2 (n_11), .ZN (n_56));
  oai211d1 g1732__7482(.A (n_14), .B (n_42), .C1 (n_49), .C2 (n_72),
       .ZN (n_54));
  aoim22d1 g1733__4733(.A1 (n_52), .A2 (n_51), .B1 (n_52), .B2 (n_51),
       .Z (n_53));
  dfnrq1 \result_reg[1] (.CP (clk), .D (n_50), .Q (result[1]));
  oai211d1 g1736__6161(.A (n_25), .B (n_34), .C1 (n_45), .C2 (n_72),
       .ZN (n_50));
  aoim21d1 g1735__9315(.A (n_41), .B1 (n_48), .B2 (n_40), .ZN (n_52));
  aoim22d1 g1737__9945(.A1 (n_48), .A2 (n_47), .B1 (n_48), .B2 (n_47),
       .Z (n_49));
  dfnrq1 \result_reg[0] (.CP (clk), .D (n_46), .Q (result[0]));
  oai211d1 g1740__2883(.A (n_16), .B (n_29), .C1 (n_28), .C2 (n_72),
       .ZN (n_46));
  aoim21d1 g1739__2346(.A (n_33), .B1 (n_44), .B2 (n_32), .ZN (n_48));
  aoim22d1 g1741__1666(.A1 (n_44), .A2 (n_43), .B1 (n_44), .B2 (n_43),
       .Z (n_45));
  aoim22d1 g1758__7410(.A1 (n_38), .A2 (n_41), .B1 (n_36), .B2 (n_40),
       .Z (n_42));
  aoim22d1 g1755__6417(.A1 (n_38), .A2 (n_37), .B1 (n_36), .B2 (n_35),
       .Z (n_39));
  aoim22d1 g1756__5477(.A1 (n_38), .A2 (n_33), .B1 (n_36), .B2 (n_32),
       .Z (n_34));
  aoim22d1 g1757__2398(.A1 (n_38), .A2 (n_3), .B1 (n_36), .B2 (n_30),
       .Z (n_31));
  aoi22d1 g1754__5107(.A1 (n_2), .A2 (n_5), .B1 (n_38), .B2 (n_6), .ZN
       (n_29));
  aoim22d1 g1759__6260(.A1 (n_27), .A2 (n_26), .B1 (n_27), .B2 (n_26),
       .Z (n_28));
  aoim22d1 g1742__4319(.A1 (n_43), .A2 (n_23), .B1 (n_22), .B2 (a[1]),
       .Z (n_25));
  aoim22d1 g1743__8428(.A1 (n_51), .A2 (n_23), .B1 (n_22), .B2 (a[3]),
       .Z (n_24));
  aoim22d1 g1753__5526(.A1 (n_38), .A2 (n_20), .B1 (n_36), .B2 (n_19),
       .Z (n_21));
  aoim22d1 g1745__6783(.A1 (n_59), .A2 (n_23), .B1 (n_22), .B2 (a[5]),
       .Z (n_18));
  aoim22d1 g1746__3680(.A1 (n_63), .A2 (n_23), .B1 (n_22), .B2 (a[6]),
       .Z (n_17));
  aoim22d1 g1747__1617(.A1 (n_27), .A2 (n_23), .B1 (n_22), .B2 (a[0]),
       .Z (n_16));
  aoim22d1 g1748__2802(.A1 (n_69), .A2 (n_23), .B1 (n_22), .B2 (a[7]),
       .Z (n_15));
  aoim22d1 g1749__1705(.A1 (n_47), .A2 (n_23), .B1 (n_22), .B2 (a[2]),
       .Z (n_14));
  aoim22d1 g1751__5122(.A1 (n_38), .A2 (n_12), .B1 (n_36), .B2 (n_11),
       .Z (n_13));
  aoim22d1 g1752__8246(.A1 (n_38), .A2 (n_9), .B1 (n_36), .B2 (n_8), .Z
       (n_10));
  aoim22d1 g1744__7098(.A1 (n_55), .A2 (n_23), .B1 (n_22), .B2 (a[4]),
       .Z (n_7));
  aoi21d1 g1750__6131(.A (n_6), .B1 (n_5), .B2 (cin), .ZN (n_44));
  inv0d0 g1760(.I (n_3), .ZN (n_4));
  ah01d1 g1761__1881(.A (a[7]), .B (b[7]), .CO (n_3), .S (n_69));
  ah01d1 g1768__5115(.A (a[6]), .B (b[6]), .CO (n_37), .S (n_63));
  ah01d1 g1767__7482(.A (a[5]), .B (b[5]), .CO (n_20), .S (n_59));
  ah01d1 g1766__4733(.A (a[4]), .B (b[4]), .CO (n_9), .S (n_55));
  ah01d1 g1765__6161(.A (a[3]), .B (b[3]), .CO (n_12), .S (n_51));
  ah01d1 g1764__9315(.A (a[2]), .B (b[2]), .CO (n_41), .S (n_47));
  ah01d1 g1763__9945(.A (a[1]), .B (b[1]), .CO (n_33), .S (n_43));
  ah01d1 g1762__2883(.A (a[0]), .B (b[0]), .CO (n_6), .S (n_27));
  inv0d0 g1770(.I (n_36), .ZN (n_2));
  nd02d1 g1774__2346(.A1 (n_1), .A2 (opcode[0]), .ZN (n_36));
  nr02d1 g1775__1666(.A1 (opcode[1]), .A2 (n_0), .ZN (n_38));
  nr02d1 g1782__7410(.A1 (opcode[0]), .A2 (n_1), .ZN (n_23));
  or03d1 g1769__6417(.A1 (opcode[1]), .A2 (opcode[2]), .A3 (opcode[0]),
       .Z (n_72));
  nr02d1 g1777__5477(.A1 (b[6]), .A2 (a[6]), .ZN (n_35));
  nr02d1 g1771__2398(.A1 (b[2]), .A2 (a[2]), .ZN (n_40));
  or02d0 g1773__5107(.A1 (a[0]), .A2 (b[0]), .Z (n_5));
  nr02d1 g1781__6260(.A1 (b[4]), .A2 (a[4]), .ZN (n_8));
  nr02d1 g1780__4319(.A1 (b[5]), .A2 (a[5]), .ZN (n_19));
  nr02d1 g1778__8428(.A1 (b[3]), .A2 (a[3]), .ZN (n_11));
  nr02d1 g1779__5526(.A1 (b[7]), .A2 (a[7]), .ZN (n_30));
  nr02d1 g1772__6783(.A1 (b[1]), .A2 (a[1]), .ZN (n_32));
  nd02d1 g1776__3680(.A1 (opcode[1]), .A2 (opcode[0]), .ZN (n_22));
  inv0d0 g1783(.I (cin), .ZN (n_26));
  inv0d0 g1784(.I (opcode[2]), .ZN (n_0));
  inv0d0 g1785(.I (opcode[1]), .ZN (n_1));
endmodule

